apiVersion: v1
kind: Service
metadata:
  name: my-crud-add-svc
  labels:
    app: crud-add
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: crud-add
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-crud-add
  labels:
    app: crud-add
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crud-add
  template:
    metadata:
      labels:
        app: crud-add
    spec:
      containers:
        - name: crud-add
          image: flokione/k8s-crud-app:latest
          ports:
            - containerPort: 80